# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app-devops-main
  labels:
    app: go-web-app-devops-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-app-devops-main
  template:
    metadata:
      labels:
        app: go-web-app-devops-main
    spec:
      containers:
      - name: go-web-app-devops-main
        image: govadoc/go-web-app-devops-main:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080