# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: go-web-app-devops-main
  labels:
    app: go-web-app-devops-main
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: go-web-app-devops-main
  type: ClusterIP
